export const GET_ERRORS = 'GET_ERRORS';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const GET_FILTERED_PRODUCTS = 'GET_FILTERED_PRODUCTS';

export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_CART = 'GET_CART';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const GET_SHIPPING_ADDRESS = 'GET_SHIPPING_ADDRESS';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORY = 'GET_CATEGORY';
